name: Docker build
on:
  push:
   branches:
    - develop
    - fix_ci_builds
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main